//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public int Id { get; set; }
        public int FkQuestionId { get; set; }
        public int FkQuizId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
