//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuiz
    {
        public int StudentQuizId { get; set; }
        public int FkStudentId { get; set; }
        public int FkQuizId { get; set; }
        public int TotalMarks { get; set; }
        public Nullable<int> LastAttendedQuestion { get; set; }
        public string Status { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual StudentQuizQuestion StudentQuizQuestion { get; set; }
    }
}
