//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuizQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentQuizQuestion()
        {
            this.StudentQuizs = new HashSet<StudentQuiz>();
        }
    
        public int SQId { get; set; }
        public int QId { get; set; }
        public int AId { get; set; }
        public Nullable<bool> Attended { get; set; }
        public int Marks { get; set; }
        public int FkStudentQuizId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentQuiz> StudentQuizs { get; set; }
    }
}
